spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/vinyldb?characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rhkdro90

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

#  flyway:
#    baselineOnMigrate: true # 스키마 히스토리 테이블 초기화

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

security:
  jwt:
    token:
      secret-key: jwt_secret_key
      access-expiration: 10000 #3600000 # 1시간
      refresh-expiration: 1209600000 # 2주

vinyl:
  init-data:
    super:
      role: ROLE_SUPER
      email: super@vinyl.com
      password: $2a$10$LYB3JRPboWY45HVnKJEWzugFXhi1Uqw37GODw71Fue3Uh42BrZmWy
      path: /**
    roles: ROLE_ADMIN,ROLE_MANAGER,ROLE_USER,ROLE_ANONYMOUS